version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8659:8000"  # Map container port 8000 to host port 8659
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1